# Questions

1. Display Top 10 Rows of The Dataset
2. Check Last 10 Rows of The Dataset
3. Check Datatype of Each Column
4. Check Null Values in the Dataset
5. How many rows and columns are there in our Dataset?
6. Highest and Lowest Purchase Prices
7. Average Purchase Price
8. How many people have French 'fr' as their Language?
9. Job Title Contains Engineer
10. Find the Email of the Person with the Following IP Address: 132.207.160.22
11. How many People have Mastercard as their Credit Card Provider and Made a Purchase Above 50?
12. Find the Email of the Person with the Following Credit Card Number: 4664825258997302
13. How many People Purchase During the AM and How Many People Purchase During PM?
14. How many People have a Credit Card that Expires in 2020?
15. What are the Top 5 Most Popular Email Providers (e.g., gmail.com, yahoo.com, etc...)?

In [9]:
import pandas as pd

In [16]:
df = pd.read_csv("D:\Python VS Code\CaseStudy_1\Ecommerce Purchases")

### 1. Display Top 10 Rows of The Dataset

In [18]:
df.head(20)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82
5,"7502 Powell Mission Apt. 768\nTravisland, VA 3...",21 XT,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_5...,Silva-Anderson,30246185196287,07/25,7169,Discover,ynguyen@gmail.com,Fish farm manager,55.96.152.147,ru,25.15
6,"93971 Conway Causeway\nAndersonburgh, AZ 75107",96 Xt,AM,Mozilla/5.0 (compatible; MSIE 7.0; Windows NT ...,Gibson and Sons,6011398782655569,07/24,714,VISA 16 digit,olivia04@yahoo.com,Dancer,127.252.144.18,de,88.56
7,"260 Rachel Plains Suite 366\nCastroberg, WV 24...",96 pG,PM,Mozilla/5.0 (X11; Linux i686) AppleWebKit/5350...,Marshall-Collins,561252141909,06/25,256,VISA 13 digit,phillip48@parks.info,Event organiser,224.247.97.150,pt,44.25
8,"2129 Dylan Burg\nNew Michelle, ME 28650",45 JN,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Galloway and Sons,180041795790001,04/24,899,JCB 16 digit,kdavis@rasmussen.com,Financial manager,146.234.201.229,ru,59.54
9,"3795 Dawson Extensions\nLake Tinafort, ID 88739",15 Ug,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.7.20) Gec...,"Rivera, Buchanan and Ramirez",4396283918371,01/17,931,American Express,qcoleman@hunt-huerta.com,Forensic scientist,236.198.199.8,zh,95.63
10,"650 Elizabeth Park\nLake Maria, LA 13526-2530",65 Yn,PM,Mozilla/5.0 (iPod; U; CPU iPhone OS 4_1 like M...,"Strickland, Michael and Gonzales",180036417827355,02/17,754,Voyager,ustewart@hotmail.com,"Development worker, community",26.59.93.1,el,96.89
11,"349 Laurie Parks\nThomasview, ID 08970",30 kK,PM,Mozilla/5.0 (X11; Linux i686; rv:1.9.6.20) Gec...,Kim-Oliver,869975209012056,06/26,9717,JCB 15 digit,johnnymiller@coleman.com,Diagnostic radiographer,128.222.40.234,en,19.26
12,"733 Heather Rest Apt. 670\nBoltonport, UT 78662",69 DO,AM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_3 ...,Moore-Martin,5115990487067905,05/26,119,VISA 16 digit,tholt@hotmail.com,"Surveyor, quantity",236.71.234.240,en,39.65
13,"118 Melton Via Suite 681\nAlexanderbury, FL 32104",36 bu,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8...,Keller PLC,4603635169938574,01/25,557,VISA 16 digit,caitlin57@yahoo.com,"Accountant, chartered public finance",84.212.92.11,it,8.93
14,"8774 Jason Keys Suite 427\nEast Scottborough, ...",70 zH,AM,Mozilla/5.0 (Windows 98; it-IT; rv:1.9.2.20) G...,"Leach, Howe and Ferguson",869967499275071,09/22,427,VISA 16 digit,aburns@yahoo.com,Acupuncturist,50.25.148.1,de,24.18
15,"31730 Chelsea Crest\nBlakemouth, CT 90395-0620",41 Cj,PM,Opera/8.95.(Windows NT 5.0; en-US) Presto/2.9....,Garcia-Steele,180069437020404,04/25,404,Diners Club / Carte Blanche,amanda39@yahoo.com,Retail manager,53.176.235.33,el,71.78
16,5283 Thomas Trafficway Suite 343\nEast Brittne...,31 ho,AM,Opera/9.73.(Windows NT 6.2; sl-SI) Presto/2.9....,"Stanton, Villanueva and Swanson",676121145525,06/22,285,Diners Club / Carte Blanche,griffincatherine@wilson.com,"Therapist, art",8.145.170.52,de,84.44
17,950 Jacqueline Village Apt. 592\nPort Kimberly...,23 Rh,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Fernandez, Melton and Gilbert",3337515540944084,01/26,771,American Express,stacymitchell@hall.com,"Designer, jewellery",223.25.125.61,el,58.68
18,"461 Christopher Square\nWest Michaelchester, C...",17 SB,PM,Mozilla/5.0 (X11; Linux i686; rv:1.9.6.20) Gec...,"Beard, Abbott and Pena",6011350184276270,12/22,767,Mastercard,hannah63@yahoo.com,Photographer,73.250.176.201,el,70.15
19,"125 Hall Summit\nBoothton, IL 41721",99 CU,PM,Mozilla/5.0 (compatible; MSIE 7.0; Windows NT ...,Turner-Mckinney,676343504830,02/20,440,VISA 16 digit,ruiznicole@gmail.com,"Designer, interior/spatial",25.105.209.214,fr,58.39

## 2. Check Last 10 Rows of The Dataset

In [19]:
df.tail(10)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
9990,"75731 Molly Springs\nWest Danielle, VT 96934-5102",93 ty,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_4;...,"Pace, Vazquez and Richards",869968197049750,04/24,877,JCB 15 digit,andersonmichael@sherman.biz,Early years teacher,54.170.3.185,ru,18.35
9991,"PSC 8165, Box 8498\nAPO AP 60327-0346",50 dA,AM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Snyder Inc,4221582137197481,02/24,969,Voyager,kking@wise-liu.com,IT sales professional,254.25.31.156,el,25.93
9992,"885 Allen Mountains Apt. 230\nWallhaven, LA 16995",40 vH,PM,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_6_5) A...,Wells Ltd,4664825258997302,10/20,431,Discover,bberry@wright.net,Set designer,174.173.51.32,de,67.96
9993,"7555 Larson Locks Suite 229\nEllisburgh, MA 34...",72 jg,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8...,Colon and Sons,30025560104631,10/25,629,Maestro,chelseawilliams@lopez.biz,"Designer, exhibition/display",177.46.82.128,el,65.61
9994,"6276 Rojas Hollow\nLake Louis, WY 56410-7837",93 Ex,PM,Opera/9.68.(X11; Linux x86_64; sl-SI) Presto/2...,Ritter-Smith,3112186784121077,01/25,1823,Maestro,iroberts@gmail.com,"Education officer, museum",242.44.112.18,zh,31.85
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59

## 3. Check Datatype of Each Column

In [22]:
df.dtypes

Address              object
Lot                  object
AM or PM             object
Browser Info         object
Company              object
Credit Card           int64
CC Exp Date          object
CC Security Code      int64
CC Provider          object
Email                object
Job                  object
IP Address           object
Language             object
Purchase Price      float64
dtype: object

## 4. Check Null Values in the Dataset

In [23]:
df.isnull()

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False,False,False,False

## Count Null

In [26]:
count_null = df.isnull().sum()
print(count_null)
print("----------------------------------------")
total_null = df.isnull().sum().sum()
print(f"total null: {total_null}")

Address             0
Lot                 0
AM or PM            0
Browser Info        0
Company             0
Credit Card         0
CC Exp Date         0
CC Security Code    0
CC Provider         0
Email               0
Job                 0
IP Address          0
Language            0
Purchase Price      0
dtype: int64
----------------------------------------
total null: 0

## 5. How many rows and columns are there in our Dataset?

In [31]:
df.shape

(10000, 14)

## 6. Highest , Lowest and Avarage Purchase Prices

In [32]:
df.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [36]:
highest = df['Purchase Price'].max()
lowest = df['Purchase Price'].min()
avg = df['Purchase Price'].mean()

In [38]:
print(f"""
    Highest Price:{highest}
    Lowest Price:{lowest}
    Avarage Price:{avg}
""")

    Highest Price:99.99
    Lowest Price:0.0
    Avarage Price:50.347302

## 8. How many people have French 'fr' as their Language?

In [39]:
df.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [63]:
df[df['Language'] == 'fr']

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
19,"125 Hall Summit\nBoothton, IL 41721",99 CU,PM,Mozilla/5.0 (compatible; MSIE 7.0; Windows NT ...,Turner-Mckinney,676343504830,02/20,440,VISA 16 digit,ruiznicole@gmail.com,"Designer, interior/spatial",25.105.209.214,fr,58.39
53,"PSC 9431, Box 7059\nAPO AA 29285-1363",14 qD,AM,Opera/9.34.(X11; Linux x86_64; it-IT) Presto/2...,"Higgins, Cardenas and Kennedy",869972604798355,08/17,157,JCB 16 digit,amorales@yahoo.com,Technical author,44.108.117.122,fr,10.41
76,"49206 Campbell Port\nNorth Cliffordshire, HI 3...",71 iu,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_5_9...,Jacobs-Tucker,6011343518820988,01/17,806,Voyager,eperez@hotmail.com,Paramedic,210.207.58.168,fr,57.34
82,493 Smith Valleys Suite 004\nNew Madelineville...,35 ls,PM,Mozilla/5.0 (iPod; U; CPU iPhone OS 4_0 like M...,"Robinson, Johnston and Valdez",4351359627548412,06/17,937,VISA 13 digit,amendez@yahoo.com,"Engineer, materials",163.129.163.100,fr,49.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9941,"43757 Brown Lodge\nValerieberg, PR 88518",68 DG,AM,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,"Jones, Williams and Dunn",6011508474487291,04/26,906,Mastercard,christian55@gmail.com,Secondary school teacher,216.118.235.145,fr,60.03
9947,"32827 Carl Inlet\nSouth Nicole, NY 38081-6636",40 Dp,PM,Mozilla/5.0 (Windows; U; Windows 95) AppleWebK...,Pruitt-Flores,3158564208754951,03/17,386,Mastercard,josephsmith@gmail.com,Textile designer,198.68.38.23,fr,49.61
9951,"518 Brown Dam\nGarciaside, IN 33057",71 wq,AM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,"Crosby, Vasquez and Ballard",5256758441931287,12/17,146,VISA 16 digit,cjennings@yahoo.com,"Lighting technician, broadcasting/film/video",58.12.83.1,fr,57.59
9977,"02182 Keith Expressway\nEast Shannon, CT 20578...",34 RL,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Deleon, Jacobson and Benton",4186094003664688,06/21,397,JCB 16 digit,daltoncarter@yahoo.com,Biomedical engineer,146.238.118.2,fr,94.93
9980,"6061 Dave Lights\nPhillipsview, UT 40500",25 Mv,AM,Opera/8.58.(Windows NT 5.0; it-IT) Presto/2.9....,Cortez-Frye,6011944199756993,12/24,755,JCB 15 digit,mark74@kirby-stewart.org,Textile designer,110.103.77.195,fr,16.05

In [52]:
df[df['Language'] == 'fr'].count()

Address             1097
Lot                 1097
AM or PM            1097
Browser Info        1097
Company             1097
Credit Card         1097
CC Exp Date         1097
CC Security Code    1097
CC Provider         1097
Email               1097
Job                 1097
IP Address          1097
Language            1097
Purchase Price      1097
dtype: int64

## 9. Job Title Contains Engineer

In [64]:
df['Job']

0       Scientist, product/process development
1                            Drilling engineer
2                     Customer service manager
3                            Drilling engineer
4                                  Fine artist
                         ...
9995                                Printmaker
9996                           Energy engineer
9997                        Veterinary surgeon
9998                  Local government officer
9999                    Embryologist, clinical
Name: Job, Length: 10000, dtype: object

In [69]:
df[df['Job'].str.contains('engineer')].count()

Address             531
Lot                 531
AM or PM            531
Browser Info        531
Company             531
Credit Card         531
CC Exp Date         531
CC Security Code    531
CC Provider         531
Email               531
Job                 531
IP Address          531
Language            531
Purchase Price      531
dtype: int64

## 10. Find the Email of the Person with the Following IP Address: 132.207.160.22

In [70]:
df.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [103]:

df[df['IP Address'] == '132.207.160.22']['Email']

2    amymiller@morales-harrison.com
Name: Email, dtype: object

## 11. How many People have Mastercard as their Credit Card Provider and Made a Purchase Above 50?

In [89]:
df.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [99]:
len(df[(df['CC Provider'] == 'Mastercard') & (df['Purchase Price'] >= 50)])

405

## 12. Find the Email of the Person with the Following Credit Card Number: 4664825258997302

In [106]:
df[df['Credit Card'] == 4664825258997302]['Email']

9992    bberry@wright.net
Name: Email, dtype: object

## 13. How many People Purchase During the AM and How Many People Purchase During PM?

In [109]:
Purchase_at_am = len(df[df['AM or PM']== 'AM'])
Purchase_at_pm = len(df[df['AM or PM']== 'PM'])

print(f"""
        Purchased At A.M = {Purchase_at_am}
        Purchased At P.M = {Purchase_at_pm}
""")

        Purchased At A.M = 4932
        Purchased At P.M = 5068

## 14. How many People have a Credit Card that Expires in 2020?

In [110]:
df['CC Exp Date']

0       02/20
1       11/18
2       08/19
3       02/24
4       10/25
        ...
9995    03/22
9996    07/25
9997    05/21
9998    11/17
9999    02/19
Name: CC Exp Date, Length: 10000, dtype: object

## 15. What are the Top 5 Most Popular Email Providers (e.g., gmail.com, yahoo.com, etc...)?